theme: jekyll-theme-slate
title: PascalAdt
description: Library of algorithms and data structures for Free Pascal

show_downloads: true

github:
  is_project_page: true
  zip_url: https://github.com/lukaszcz/pascaladt/archive/refs/tags/v1.0.zip
  gz_url: https://github.com/lukaszcz/pascaladt/archive/refs/tags/v1.0.tar.gz
  repository_url: "https://github.com/lukaszcz/pascaladt"
  repository_name: PascalAdt
  owner_url: "https://lukaszcz.github.io"
  owner_name: "Lukasz Czajka"
